version: '3.8'

services:
  bot-core:
    build:
      context: .
    container_name: bot-core
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    restart: always